### ISSUE TITLE
Decide on TEI

### ISSUE THREAD

**Issue by richiebful** [mtm80/russ-project#10]
due: Friday, 9 February

I am personally **in favor** of using TEI. Why?
- TEI should be relatively straightforward to use for our project, since it is designed for text-based markup
- <s>Using TEI's precooked XSLT will make webpage presentation of the text much easier</s>
- Learning the format will come in handy on future research projects, especially if grant money is involved

Feel free to discuss/vote below.

**Comment by djbpitt** [comment]
The decision is up to the three of you, so I’m not going to vote. But, for what it’s worth, Richie’s first and third points make good sense to me. I’m less confident about the middle one because the limitation with using precooked XSLT is that you don’t have good control over the output. For that reason, when I use TEI, I always write my own XSLT to transform it. On the other hand, transforming TEI isn’t any harder than transforming any other XML, so that’s sort of a neutral category for me.

**Comment by mtm80** [comment]
After looking over the TEI article, I feel somewhat ambivalent about the prospect of using TEI for the project.  This is new territory for me so I'm not entirely confident of my understanding of it.  The header article seemed to me to be a useful tool as a reference.  It can log all of our activity and serve as a background document for whoever reads our research later.  Overall, I would be fine with using TEI for our project.

**Comment by richiebful** [comment]
I'm moving ahead on the ODD file now. I should have a schema for speeches by Monday so we can start marking up documents.
