### ISSUE TITLE
Project issue Feb. 7, 2018

### ISSUE THREAD

**Issue by mtm80** [mtm80/russ-project#11]
Based on our last meeting on Monday, we still have not settled on a firm direction for our research.  We are still exploring possibilities though we will be focusing on a handful of candidates which so far include Putin, Zhirinovsky, and Grudinin.  We are considering to concentrate on a particular campaign issue such as the economy, foreign relations, or immigration.  We are also debating on whether or not we will use TEI for the project though for now, it looks as though we probably will do so.  Campaign and party websites will be further explored for speech transcripts and content will be further analyzed for common and recurring themes.   These themes will determine how we progress in the coming weeks.

**Comment by Idi0teque** [comment]
How wide of a body of text do you think you'll be looking at? Are there any books you're considering with regards to markup, or are you just going to use websites and fliers? This project sounds super cool by the way; I don't know the election date, but will we pass it during the semester? If so, will you be radically changing your project should political developments occur?

**Comment by brucknerp** [comment]
Narrowing your project's focus to one specific issue might be a better idea in the long run, since you can hone in on key elements to analyze instead of spreading yourselves too thin. This initial document analysis one of the most important steps--I like that your group is taking proper time to consider all aspects. 

How are you deciding which candidates to focus on and which to pass over? Also, have you determined the quantity of text you plan to analyze per candidate?
