### ISSUE TITLE
Compile speech/interview transcripts of Zhirinovsky

### ISSUE THREAD

**Issue by djbpitt** [mtm80/russ-project#18]

**Comment by mtm80** [comment]
I attempted to make a txt file of one of the Zhirinovsky speeches but Oxygen was unable to save it since it does not support Russian letters.  This was the error message.

Cannot save the file: Some of the characters cannot be represented in the current encoding: "Cp1252". Please change the encoding of the document. For instance you can use "UTF-8" or "UTF-16", since these encodings accept any Unicode character. Total number of characters that cannot be represented: 127.

Here are some of these characters:

В (0x412) at line 1 column 1
ы (0x44b) at line 1 column 2
с (0x441) at line 1 column 3
т (0x442) at line 1 column 4
у (0x443) at line 1 column 5
п (0x43f) at line 1 column 6
л (0x43b) at line 1 column 7
е (0x435) at line 1 column 8
н (0x43d) at line 1 column 9
и (0x438) at line 1 column 10
е (0x435) at line 1 column 11
о (0x43e) at line 1 column 13
б (0x431) at line 1 column 14
л (0x43b) at line 1 column 15
е (0x435) at line 1 column 16
ч (0x447) at line 1 column 17
ё (0x451) at line 1 column 18
н (0x43d) at line 1 column 19
н (0x43d) at line 1 column 20
о (0x43e) at line 1 column 21

**Comment by djbpitt** [comment]
Please commit and push your texts, even though they seem to be unreadable. You can create a raw/zhirinovsky subdirectory alongside the existing raw/putin one, and put them there.

The issue isn't that &lt;oXgyen/&gt; can't read Russian (it can); it's that the files you found are not in Unicode. There are several competing ways to represent Russian on line, the files you found use an old one, and &lt;oXygen/&gt; (and XML in general) works reliably only with Unicode, which is the newer standard. It isn't all that new (it started to be developed in the 1980s), but there are still sites that haven't migrated from stone-age encodings to Unicode, and apparently the Zhirinovsky files live on one of those.

If you Google for a combination of "convert" "Russian" and "Unicode", you should find many online conversion utilities, where you can copy and paste your non-Unicode input text, push a button, and get the same text back in Unicode. If it gives you a choice of output formats, choose "UTF-8" (might be upper or lower case, may or may not have a hyphen). Once you get the new version back, verify that it's okay in &lt;oXygen;&gt;. If it is, use the new versions to replace the old. If it isn't, please post a follow-up inquiry here and we'll help you troubleshoot further.
