### ISSUE TITLE
Project Issue Feb. 14, 2018

### ISSUE THREAD

**Issue by mtm80** [mtm80/russ-project#19]
Based on our meeting on Monday, we are continuing to compile speech and interview texts for analysis and mark-up.  We're using party websites and news media outlets as sources.  A schema has been created for the texts that we will be using and we're aiming at roughly 5 texts per candidate.  We're beginning to build a site to display our work also.  We are also exploring other texts for possible insights into methodologies that we could implement in our own research.

**Comment by djbpitt** [comment]
I see the ODD in the repo, but not the schema. Let me know if you have any questions about using the ODD to generate a Relax NG schema. I do it using a transformation scenario inside &lt;oXygen/&gt;; there is also a transformation scenario that will generate HTML documentation for your customization of TEI, and I'd recommend creating the documentation, as well.

**Comment by brucknerp** [comment]
Does this mean that you guys are not focusing on a single campaign issue, but just each candidate's campaign overall? You mentioned that in an earlier issue.

Also, since your texts are coming from originally oral sources, are you measuring any sort of non-textual based content? (type of delivery, etc) I tried looking at your texts to see but I got lost in the Russian, haha.
