### ISSUE TITLE
Lemmatizing Russian

### ISSUE THREAD

**Issue by richiebful** [mtm80/russ-project#23]
Is there an accepted authority for lemmatizing Russian text out there? The [Yandex Mystem](https://tech.yandex.ru/mystem/) project seems promising. There's also a [Python wrapper](https://github.com/nlpub/pymystem3) that would make it easier to lemmatize in-place on the XML. I was thinking this would be helpful if we decide to do topic modelling.

**Comment by djbpitt** [comment]
Yandex Mystem has received good reviews, but I've never used it. The dictionary that Elise and I have been building is accessible, and we can show you how to interact with it, but it's still missing a lot of lexemes, so if you can get decent results from Mystem, I think that's a better choice for now. Not to mention that, since I've never used it myself, I'd be eager to learn how it performs in your experience.

Intuitively it seems as if lemmatization would improve topic-modeling performance, especially with relatively short texts. It might be interesting to run the same texts with and without lemmatization, though, to see whether there is a difference in practice.
