### ISSUE TITLE
Project Update 18-04-2018

### ISSUE THREAD

**Issue by richiebful** [mtm80/russ-project#88]
Our [website](http://ru-rhetoric.obdurodon.org/) is starting to solidify and take shape, and we're uploading a lot of content to fill it all out. 

This past week, we wrote a lot of documentation for methodology and started work on the analysis. We added a drop-down menu and a few other bells and whistles to the site. 

Next week, we are focusing on four main areas: website tweaks, content writing, coding tweaks, and visualizations,

**Website tweaks**
- fix a few aesthetic issues with the reading view (change topic model bolding, map tag names to title)
- replace SVG lines with ```<hr/>``` tags
- shrink header
- make dropdown links go somewhere
- get *all* the content up there

**Content Writing**
- start working on Russian version of the site
- begin work on the analysis using the topic model data, rhetorical tag data

**Visualizations**
- create visualization for common rhetorical devices
- create visualization for topics

**Comment by JosephDRogers23** [comment]
I love your website and how it's taking shape! I especially like the interactivity with the site. How do you think you'll implement the Russian language version of the site? Will this be an on/off toggle for the whole site, or per page, or something else entirely?

**Comment by richiebful** [comment]
The Russian version is just going to be a hard-coded toggle for a couple of the pages, mostly because of time constraints. They'll likely be shorter too, as opposed to full translations. If I'm feeling ambitious after Tuesday (my last final), maybe I'll try doing a server-side toggle in a branch. If I do, I'll write an issue about it on the dh_course repo.

**Comment by jachinn** [comment]
While your dropdown menu is nice, it might not be the best way to navigate-- the menu barely fits on my monitor. It might work to reduce the vertical padding on each item in the dropdown, but it might also be worth adding a link that goes to a page which just lists all the speeches.

I see you're using includes to add your menu to your other pages-- is there a reason you haven't added it to your speeches subpages yet?

I like the buttons on the right of your reading view that highlight different text features. Do you think it makes the page too busy to allow highlighting multiple features at once? I think this would make it easier to compare the use of different rhetorical devices and/or topics. It might also be good to put counts next to each of the devices in that right hand pane. I assume the items are ordered by number of occurrences, but this is not obvious to the average user and anyone looking to compare multiple speeches will likely have some trouble finding which device they wanted to look at since the order is different from speech to speech.

**Comment by brucknerp** [comment]
I really like the slightly less vibrant color scheme and your updated layout! I also like the button/toggle features for navigating the text. The only thing I thought was that the red for rhetorical devices stands out more than the bold for topics does, so maybe a small change to the formatting for topics would make it a little more readable...
