### ISSUE TITLE
Write schema for speeches

### ISSUE THREAD

**Issue by richiebful** [mtm80/russ-project#9]
Either write a schema or ODD file to constrain our XML for speech markup, pending our decision on to use TEI or not.

**Comment by djbpitt** [comment]
There were two problems with the ODD:

1. `<text>` should contain `<body>`, which should contain `<div>`, which should contain `<schemaSpec>`. I added the missing intermediate levels.
1. The elements selected from the`core` module did not include `<teiCorpus>` (the designated start point), and perhaps others. I removed the restriction, thus including the entire `core` module.

You should probably reintroduce restrictions on the `core` to exclude stuff you really don’t need, but I’d suggest approaching that carefully, so that if you remove something necessary, you’ll be notified immediately and can put it back.
